version: '3.8'

services:
  youtube-bot:
    build: .
    container_name: youtube-downloader-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./temp_downloads:/app/temp_downloads
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
